### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by Success1308** [djneill/Simple-Mario-Character-API#2]
Not working.

**Comment by djneill** [comment]
Thank you for bringing this to my attention, @Success1308. It appears that the API was hosted on Cyclic.sh, which is no longer in business. I will look into moving it to a different hosting provider over the weekend. I appreciate your patience.

**Comment by djneill** [comment]
I went ahead and moved it over real quick. This is an old project from when I first started learning Node, and APIs.

**Comment by Success1308** [comment]
no problem!
